"use strict";

(function () {

    Object.defineProperty(exports, "__esModule", {value: true});
    exports.plugin = exports.details = void 0;

    /**
     * Delete MP4 Plugin
     * - Deletes the MP4 file generated by Build DV5 MP4 or Build DV8.1 MP4 plugins
     * - Reads the file path from args.variables.generatedMp4Path
     */

    const fs = require("fs");
    const path = require("path");

    // Log helper (mirrors console + job log)
    function log(jobLog, msg) {
        jobLog(msg);
        console.log(msg);
    }

    // Resolve inputs that may be wrapped in {{{ }}} to reference args.* values
    function resolveInput(value, args) {
        if (typeof value !== "string") return value;
        const match = value.match(/^\{\{\{\s*(.+?)\s*\}\}\}$/);
        if (!match) return value;

        const baseExpr = match[1].trim();
        const attempts = [baseExpr];

        // Support both args.variables.user.* (old) and args.variables.* (new)
        const userPrefixes = ["args.variables.user.", "variables.user."];
        userPrefixes.forEach((prefix) => {
            if (baseExpr.startsWith(prefix)) {
                attempts.push(baseExpr.replace(prefix, prefix.replace(".user", "")));
            }
        });

        for (const expr of attempts) {
            try {
                const fn = new Function("args", `return ${expr};`);
                const resolved = fn(args);
                if (resolved !== undefined && resolved !== null) return resolved;
            } catch (err) {
                console.warn(`Failed to resolve placeholder ${value} with expr "${expr}": ${err.message}`);
            }
        }

        // Unresolved placeholders should not propagate as literal "{{{...}}}"
        return "";
    }

    const details = () => ({
        name: "Delete Generated MP4",
        description: "Deletes the MP4 file created by Build DV5 MP4 or Build DV8.1 MP4 plugins.",
        style: {borderColor: "red"},
        tags: "video",
        isStartPlugin: false,
        pType: "",
        requiresVersion: "2.11.01",
        sidebarPosition: 10,
        icon: "faTrash",
        inputs: [
            {
                label: "MP4 File Path",
                name: "mp4FilePath",
                tooltip: "Path to the MP4 file to delete. Defaults to the file generated by Build DV5/DV8.1 MP4 plugins.",
                inputType: "string",
                defaultValue: "{{{args.variables.generatedMp4Path}}}",
                inputUI: { type: "directory" },
            },
        ],
        outputs: [{number: 1, tooltip: "Continue to next step"}],
    });
    exports.details = details;

    const plugin = async (args) => {
        const lib = require("../../../../../methods/lib")();
        args.inputs = lib.loadDefaultValues(args.inputs, details);

        const jobLog = args.jobLog;
        log(jobLog, "=== Delete Generated MP4 Plugin Start ===");

        const inputFileObj = args.inputFileObj;

        const mp4FilePath = (resolveInput(args.inputs.mp4FilePath, args) || "").toString().trim();

        if (!mp4FilePath) {
            log(jobLog, "🚫 No MP4 file path provided. Make sure this plugin runs after Build DV5 MP4 or Build DV8.1 MP4.");
            return {
                outputFileObj: inputFileObj,
                outputNumber: 1,
                variables: args.variables
            };
        }

        if (!fs.existsSync(mp4FilePath)) {
            log(jobLog, `⚠️ MP4 file not found: ${mp4FilePath}`);
            return {
                outputFileObj: inputFileObj,
                outputNumber: 1,
                variables: args.variables
            };
        }

        try {
            fs.unlinkSync(mp4FilePath);
            log(jobLog, `🗑️ Successfully deleted MP4 file: ${mp4FilePath}`);
        } catch (err) {
            log(jobLog, `🚨 Failed to delete MP4 file: ${err.message}`);
            throw err;
        }

        log(jobLog, "=== Delete Generated MP4 Plugin End ===");

        return {
            outputFileObj: inputFileObj,
            outputNumber: 1,
            variables: args.variables
        };
    };

    exports.plugin = plugin;

})();  // END WRAPPER
